name: Deploy múltiple carpetas a GitHub Pages con separación limpia

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4

    - name: Configurar Git en master
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Clonar gh-pages branch en carpeta output/
      run: |
        git clone --single-branch --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} output || mkdir output

    - name: Sincronizar carpetas (borrar las eliminadas)
      run: |
        MAIN_DIRS=$(ls -d */ | sed 's#/##')
        cd output
        for dir in */; do
          dir=${dir%/}
          if [ "$dir" != "CNAME" ]; then
            if ! echo "$MAIN_DIRS" | grep -q "^$dir$"; then
              echo "Borrando demo eliminado: $dir"
              rm -rf "$dir"
            fi
          fi
        done
        cd ..

    - name: Copiar nuevas carpetas y actualizar existentes
      run: |
        for dir in $(ls -d */); do
          dir=${dir%/}
          if [ "$dir" != "output" ]; then
            echo "Actualizando demo: $dir"
            mkdir -p output/$dir
            cp -r $dir/* output/$dir/
          fi
        done

    - name: Copiar archivo CNAME
      run: |
        cp CNAME output/CNAME

    - name: Commit y Push a gh-pages
      run: |
        cd output
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add .
        git commit -m "Sync automático: actualizar, agregar y borrar demos, mantener CNAME" || echo "No hay cambios"
        git push origin gh-pages
